---
language: node_js
node_js:
  - "4.2"

sudo: false

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt@2
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
